function tCross = ...
    interpolateCrossing( ...
    t0,...
    t1,...
    gap0,...
    gap1,...
    threshold)

alpha = ...
    (gap0 - threshold) / ...
    (gap0 - gap1);

alpha = min(max(alpha,0),1);

tCross = t0 + alpha*(t1 - t0);

end